version: '3'
services:
  api:
    image: node:14-alpine
    command: yarn start:dev
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - backend
    ports:
      - "3000:3000"
  blog:
    image: node:14-alpine
    command: yarn start:dev blog
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - backend
    hostname: 'blog'
  user:
    image: node:14-alpine
    command: yarn start:dev user
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - backend
    hostname: 'user'

networks:
  backend:
    driver: bridge
